spring:
  application:
    name: mg-sms
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8763
server:
  port: 8763
