spring:
  application:
    name: mg-core
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8762
server:
  port: 8762 #service0 占用8762
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 40000  # feign 超时控制
mg-sms:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  
mg-dd:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  
mg-wx:
  ribbon:
    ReadTimeout: 1000
    ConnectTimeout: 500
    MaxAutoRetries: 1  # SR6版本,这里设为1,会重试3次,重试次数还和另外的两个值有关
